namespace Atc.Kusto.Analyzer.Tests.Rules.Usage;

#pragma warning disable SA1135 // Using directives must be qualified
using AnalyzerVerifier = CSharpAnalyzerVerifier<MissingKustoScriptResourceAnalyzer>;
#pragma warning restore SA1135 // Using directives must be qualified

[SuppressMessage("", "AsyncFixer01:The method does not need to use async/await", Justification = "OK - Test code")]
[SuppressMessage("Naming", "MA0048:File name must match type name", Justification = "OK - Partial class")]
public sealed partial class MissingKustoScriptResourceAnalyzerTests
{
    [Fact]
    public async Task NoDiagnostic_AbstractClass()
    {
        const string code = """
                            namespace Atc.Kusto;

                            public abstract class KustoScript
                            {
                            }

                            public abstract class MyQuery : KustoScript
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_InterfaceType()
    {
        const string code = """
                            namespace Atc.Kusto;

                            public interface IKustoScript
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_ClassNotInheritingFromKustoScript()
    {
        const string code = """
                            public class MyClass
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_AutoGeneratedFile()
    {
        const string code = """
                            // <auto-generated />
                            namespace Atc.Kusto;

                            public abstract class KustoScript
                            {
                            }

                            public class MyQuery : KustoScript
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }

    [Fact]
    public async Task NoDiagnostic_AutoGeneratedFileCaseInsensitive()
    {
        const string code = """
                            // This file is AUTO-GENERATED by code generator
                            namespace Atc.Kusto;

                            public abstract class KustoScript
                            {
                            }

                            public class MyQuery : KustoScript
                            {
                            }
                            """;

        await AnalyzerVerifier.VerifyAnalyzerAsync(code);
    }
}