<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Queries\CustomerByIdQuery.kusto" />
    <None Remove="Queries\CustomerSalesQuery.kusto" />
    <None Remove="Queries\CustomersSplitByGenderQuery.kusto" />
    <None Remove="Queries\StormEventsQuery.kusto" />
    <None Remove="Queries\CustomersStreamingQuery.kusto" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Queries\CustomerByIdQuery.kusto" />
    <EmbeddedResource Include="Queries\CustomerSalesQuery.kusto" />
    <EmbeddedResource Include="Queries\CustomersSplitByGenderQuery.kusto" />
    <EmbeddedResource Include="Queries\StormEventsQuery.kusto" />
    <EmbeddedResource Include="Queries\CustomersStreamingQuery.kusto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Atc.Kusto\Atc.Kusto.csproj" />
  </ItemGroup>

</Project>
