<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>Atc.Kusto</PackageId>
    <PackageTags>adx;kusto;azure</PackageTags>
    <Description>Atc.Kusto contains a .NET library designed to facilitate the execution of Kusto queries and commands within Azure Data Explorer environments</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="HealthChecks\KustoHealthCheckQuery.kusto" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="HealthChecks\KustoHealthCheckQuery.kusto" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Atc" Version="2.0.555" />
    <PackageReference Include="Microsoft.Azure.Kusto.Data" Version="14.2.2" />
    <PackageReference Include="Microsoft.Azure.Kusto.Ingest.V2" Version="[0.0.9]" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.8.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Atc.Kusto.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <!-- Package the Roslyn analyzer and code fixes with this NuGet package -->
  <ItemGroup>
    <ProjectReference Include="..\Atc.Kusto.Analyzer\Atc.Kusto.Analyzer.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\Atc.Kusto.Analyzer.CodeFixes\Atc.Kusto.Analyzer.CodeFixes.csproj" PrivateAssets="all" />
    <None Include="..\Atc.Kusto.Analyzer\bin\$(Configuration)\netstandard2.0\Atc.Kusto.Analyzer.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="..\Atc.Kusto.Analyzer.CodeFixes\bin\$(Configuration)\netstandard2.0\Atc.Kusto.Analyzer.CodeFixes.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

</Project>
