namespace Atc.Kusto;

/// <summary>
/// Represents the result of a streaming query executed against a Kusto data source.
/// This class encapsulates the asynchronous stream of data rows returned by the query, along with optional metadata
/// such as the dataset header, table schemas, and query completion summary.
/// </summary>
/// <typeparam name="T">The type representing each row in the query result.</typeparam>
public sealed class StreamingQueryResult<T>
{
    /// <summary>
    /// Gets or sets the asynchronous stream of data rows generated by the query.
    /// </summary>
    public IAsyncEnumerable<T> Rows { get; set; } = null!;

    /// <summary>
    /// Gets or sets the dataset header, containing metadata about the query result, if requested.
    /// </summary>
    public KustoDataSetHeader? Header { get; set; }

    /// <summary>
    /// Gets or sets the collection of table schemas describing the structure of the result tables, if requested.
    /// </summary>
    public IList<KustoTableSchema>? TableSchemas { get; } = [];

    /// <summary>
    /// Gets or sets the query completion summary, which provides details about the execution status of the query, if requested.
    /// </summary>
    public KustoResultCompletion? Completion { get; set; }
}