<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="**/*.kusto" />
    <AdditionalFiles Include="**/*.kusto" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Atc.Kusto\Atc.Kusto.csproj" />
  </ItemGroup>

</Project>
