namespace Atc.Kusto.Analyzer.Rules.Usage;

/// <summary>
/// Analyzer that detects empty .kusto embedded resource files.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class EmptyKustoScriptFileAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor Rule = new(
        RuleIdentifierConstants.Usage.EmptyKustoScriptFile,
        title: "Empty .kusto embedded resource file",
        messageFormat: "Class '{0}' has a corresponding .kusto file '{1}' that is empty or contains only comments. Add a valid Kusto query or command.",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Classes inheriting from KustoScript should have a .kusto file with actual query or command content, not just comments or whitespace.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.EmptyKustoScriptFile));

    private static readonly Regex SingleLineCommentRegex = new(@"//.*?$", RegexOptions.Multiline);
    private static readonly Regex MultiLineCommentRegex = new(@"/\*.*?\*/", RegexOptions.Singleline);
    private static readonly Regex ParameterDeclarationRegex = new(@"declare\s+query_parameters\s*\([^)]*\)\s*;", RegexOptions.Singleline | RegexOptions.IgnoreCase);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];

    public override void Initialize(AnalysisContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var namedTypeSymbol = (INamedTypeSymbol)context.Symbol;

        if (!ShouldAnalyzeSymbol(namedTypeSymbol))
        {
            return;
        }

        var syntaxReference = GetValidSyntaxReference(namedTypeSymbol);
        if (syntaxReference is null || syntaxReference.SyntaxTree.IsAutoGeneratedFile())
        {
            return;
        }

        var classFilePath = syntaxReference.SyntaxTree.FilePath;
        if (string.IsNullOrEmpty(classFilePath))
        {
            return;
        }

        var kustoFile = FindKustoFile(context.Options.AdditionalFiles, classFilePath);
        if (kustoFile is null)
        {
            // No .kusto file found - ATCK301 will handle this
            return;
        }

        // Check if the .kusto file is empty
        if (!IsKustoFileEmpty(kustoFile, context.CancellationToken))
        {
            // File has content, no diagnostic needed
            return;
        }

        var identifier = GetTypeIdentifier(syntaxReference, context.CancellationToken);
        if (identifier is null)
        {
            return;
        }

        var diagnostic = Diagnostic.Create(
            Rule,
            identifier.Value.GetLocation(),
            namedTypeSymbol.Name,
            kustoFile.Path.GetFileName());

        context.ReportDiagnostic(diagnostic);
    }

    private static bool ShouldAnalyzeSymbol(INamedTypeSymbol namedTypeSymbol)
    {
        // Skip if this is an abstract class, interface, or not a class/record
        if (namedTypeSymbol.IsAbstract || (namedTypeSymbol.TypeKind != TypeKind.Class && namedTypeSymbol.TypeKind != TypeKind.Struct))
        {
            return false;
        }

        return InheritsFromKustoScript(namedTypeSymbol);
    }

    private static SyntaxReference? GetValidSyntaxReference(INamedTypeSymbol namedTypeSymbol)
    {
        var syntaxReferences = namedTypeSymbol.DeclaringSyntaxReferences;
        return syntaxReferences.Length > 0 ? syntaxReferences[0] : null;
    }

    private static AdditionalText? FindKustoFile(ImmutableArray<AdditionalText> additionalFiles, string classFilePath)
    {
        var classFileName = classFilePath.GetFileNameWithoutExtension();
        var classDirectory = classFilePath.GetDirectoryName();
        var expectedKustoFileName = $"{classFileName}.kusto";

        // Find the corresponding .kusto file in AdditionalFiles
        // Match by both filename and directory to handle multiple files with the same name
        return additionalFiles.FirstOrDefault(file =>
        {
            if (string.IsNullOrEmpty(file.Path))
            {
                return false;
            }

            var fileName = file.Path.GetFileName();
            if (!fileName.Equals(expectedKustoFileName, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            var fileDirectory = file.Path.GetDirectoryName();
            return fileDirectory.Equals(classDirectory, StringComparison.OrdinalIgnoreCase);
        });
    }

    private static bool IsKustoFileEmpty(AdditionalText kustoFile, CancellationToken cancellationToken)
    {
        var fileText = kustoFile.GetText(cancellationToken);
        if (fileText is null)
        {
            return true;
        }

        var content = fileText.ToString();

        // Quick check: if completely empty or whitespace, it's empty
        if (string.IsNullOrWhiteSpace(content))
        {
            return true;
        }

        // Remove single-line comments (// ...)
        var withoutSingleLineComments = SingleLineCommentRegex.Replace(content, string.Empty);

        // Remove multi-line comments (/* ... */)
        var withoutComments = MultiLineCommentRegex.Replace(withoutSingleLineComments, string.Empty);

        // Remove declare query_parameters declarations
        var withoutParameters = ParameterDeclarationRegex.Replace(withoutComments, string.Empty);

        // Check if anything remains after trimming
        return string.IsNullOrWhiteSpace(withoutParameters);
    }

    private static SyntaxToken? GetTypeIdentifier(SyntaxReference syntaxReference, CancellationToken cancellationToken)
    {
        var declaration = syntaxReference.GetSyntax(cancellationToken);

        return declaration switch
        {
            ClassDeclarationSyntax classDecl => classDecl.Identifier,
            RecordDeclarationSyntax recordDecl => recordDecl.Identifier,
            _ => null,
        };
    }

    private static bool InheritsFromKustoScript(INamedTypeSymbol typeSymbol)
    {
        var baseType = typeSymbol.BaseType;

        while (baseType != null)
        {
            if (baseType.Name == Constants.KustoScriptBaseClassName)
            {
                return true;
            }

            baseType = baseType.BaseType;
        }

        return false;
    }
}