namespace Atc.Kusto.Analyzer.Rules.Usage;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class KustoParameterMismatchAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor ParameterCountMismatchRule = new(
        RuleIdentifierConstants.Usage.ParameterCountMismatch,
        title: "Parameter count mismatch between C# and Kusto",
        messageFormat: "Parameter count mismatch: C# has {0} parameter(s), Kusto declares {1}",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "The number of parameters in the C# class must match the number of parameters declared in the corresponding .kusto file.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.ParameterCountMismatch));

    private static readonly DiagnosticDescriptor ParameterTypeMismatchRule = new(
        RuleIdentifierConstants.Usage.ParameterTypeMismatch,
        title: "Parameter type mismatch between C# and Kusto",
        messageFormat: "Parameter '{0}' type mismatch: C# expects '{1}', Kusto declares '{2}'",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Parameter types in the C# class must be compatible with the types declared in the corresponding .kusto file.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.ParameterTypeMismatch));

    private static readonly DiagnosticDescriptor ParameterOrderMismatchRule = new(
        RuleIdentifierConstants.Usage.ParameterOrderMismatch,
        title: "Parameter order mismatch between C# and Kusto",
        messageFormat: "Parameter order mismatch: C# position {0} is '{1}', Kusto position {0} is '{2}'",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Parameters in the C# class must appear in the same order as declared in the corresponding .kusto file.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.ParameterOrderMismatch));

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
        => [ParameterCountMismatchRule, ParameterTypeMismatchRule, ParameterOrderMismatchRule];

    public override void Initialize(AnalysisContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var namedTypeSymbol = (INamedTypeSymbol)context.Symbol;

        if (!KustoAnalyzerHelper.ShouldAnalyzeSymbol(namedTypeSymbol))
        {
            return;
        }

        var syntaxReference = KustoAnalyzerHelper.GetSyntaxReference(namedTypeSymbol);
        if (syntaxReference is null || syntaxReference.SyntaxTree.IsAutoGeneratedFile())
        {
            return;
        }

        var classFilePath = syntaxReference.SyntaxTree.FilePath;
        if (string.IsNullOrEmpty(classFilePath))
        {
            return;
        }

        var kustoFile = KustoAnalyzerHelper.FindKustoFile(context.Options.AdditionalFiles, classFilePath);
        if (kustoFile is null)
        {
            // No .kusto file found - ATCK301 will handle this
            return;
        }

        var kustoParameters = GetKustoParameters(kustoFile, context.CancellationToken);
        if (kustoParameters is null)
        {
            return;
        }

        var csharpParameters = GetPrimaryConstructorParameters(namedTypeSymbol);
        var location = KustoAnalyzerHelper.GetDiagnosticLocation(syntaxReference, context.CancellationToken);
        if (location is null)
        {
            return;
        }

        ValidateParameters(context, location, csharpParameters, kustoParameters);
    }

    private static IReadOnlyList<Parsing.KustoParameter>? GetKustoParameters(
        AdditionalText kustoFile,
        CancellationToken cancellationToken)
    {
        var kustoFileText = kustoFile.GetText(cancellationToken);
        if (kustoFileText is null)
        {
            return null;
        }

        var kustoContent = kustoFileText.ToString();
        return Parsing.KustoParameterParser.ParseParameters(kustoContent);
    }

    private static void ValidateParameters(
        SymbolAnalysisContext context,
        Location location,
        List<(string Name, string Type)> csharpParameters,
        IReadOnlyList<Parsing.KustoParameter> kustoParameters)
    {
        // Validate parameter count
        if (csharpParameters.Count != kustoParameters.Count)
        {
            var diagnostic = Diagnostic.Create(
                ParameterCountMismatchRule,
                location,
                csharpParameters.Count,
                kustoParameters.Count);
            context.ReportDiagnostic(diagnostic);
            return; // Early exit - no point checking type/order if count doesn't match
        }

        // Validate parameter order and types
        for (var i = 0; i < csharpParameters.Count; i++)
        {
            var csharpParam = csharpParameters[i];
            var kustoParam = kustoParameters[i];

            // Check name (order) - case-insensitive comparison
            if (!csharpParam.Name.Equals(kustoParam.Name, StringComparison.OrdinalIgnoreCase))
            {
                var diagnostic = Diagnostic.Create(
                    ParameterOrderMismatchRule,
                    location,
                    i,
                    csharpParam.Name,
                    kustoParam.Name);
                context.ReportDiagnostic(diagnostic);
                return; // Stop after first order mismatch
            }

            // Check type compatibility
            if (!IsTypeCompatible(csharpParam.Type, kustoParam.Type))
            {
                var diagnostic = Diagnostic.Create(
                    ParameterTypeMismatchRule,
                    location,
                    csharpParam.Name,
                    csharpParam.Type,
                    kustoParam.Type);
                context.ReportDiagnostic(diagnostic);
            }
        }
    }

    private static List<(string Name, string Type)> GetPrimaryConstructorParameters(
        INamedTypeSymbol typeSymbol)
    {
        var parameters = new List<(string Name, string Type)>();

        // For records, parameters are properties
        // For classes with primary constructors (C# 12+), they are also properties
        // We look for the primary constructor
        var primaryConstructor = typeSymbol.Constructors
            .FirstOrDefault(c => c.Parameters.Length > 0 && !c.IsImplicitlyDeclared);

        if (primaryConstructor is not null)
        {
            foreach (var param in primaryConstructor.Parameters)
            {
                var typeName = GetCSharpTypeName(param.Type);
                parameters.Add((param.Name, typeName));
            }
        }

        return parameters;
    }

    private static string GetCSharpTypeName(ITypeSymbol typeSymbol)
    {
        // Handle nullable value types
        if (typeSymbol is INamedTypeSymbol { IsGenericType: true, OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } namedType)
        {
            var underlyingType = namedType.TypeArguments[0];
            return GetCSharpTypeName(underlyingType);
        }

        // Handle nullable reference types - treat as non-nullable for type matching
        var nonNullableType = typeSymbol.WithNullableAnnotation(NullableAnnotation.NotAnnotated);

        return nonNullableType.SpecialType switch
        {
            SpecialType.System_Int64 => "long",
            SpecialType.System_Int32 => "int",
            SpecialType.System_String => "string",
            SpecialType.System_Boolean => "bool",
            SpecialType.System_Double => "double",
            SpecialType.System_Decimal => "decimal",
            _ => nonNullableType.Name switch
            {
                "DateTime" => "DateTime",
                "Guid" => "Guid",
                "TimeSpan" => "TimeSpan",
                _ => nonNullableType.Name,
            },
        };
    }

    private static bool IsTypeCompatible(
        string csharpType,
        string kustoType)
    {
        // Type mapping: C# -> Kusto
        var typeMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "long", "long" },
            { "int", "int" },
            { "string", "string" },
            { "DateTime", "datetime" },
            { "bool", "bool" },
            { "double", "real" },
            { "decimal", "decimal" },
            { "Guid", "guid" },
            { "TimeSpan", "timespan" },
        };

        if (typeMap.TryGetValue(csharpType, out var expectedKustoType))
        {
            return expectedKustoType.Equals(kustoType, StringComparison.OrdinalIgnoreCase);
        }

        // If no mapping found, compare directly (case-insensitive)
        return csharpType.Equals(kustoType, StringComparison.OrdinalIgnoreCase);
    }
}