namespace Atc.Kusto.Analyzer.Rules.Usage;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class MissingKustoScriptResourceAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor Rule = new(
        RuleIdentifierConstants.Usage.MissingKustoScriptResource,
        title: "Missing .kusto embedded resource file",
        messageFormat: "Class '{0}' inherits from KustoScript but the corresponding embedded resource '{1}' was not found. Ensure the .kusto file exists and is marked as an embedded resource.",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Classes inheriting from KustoScript must have a corresponding .kusto file as an embedded resource with a name matching the fully qualified class name.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.MissingKustoScriptResource));

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];

    public override void Initialize(AnalysisContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var namedTypeSymbol = (INamedTypeSymbol)context.Symbol;

        // Skip if this is an abstract class, interface, or not a class
        if (namedTypeSymbol.IsAbstract || namedTypeSymbol.TypeKind != TypeKind.Class)
        {
            return;
        }

        // Check if the class inherits from KustoScript
        if (!InheritsFromKustoScript(namedTypeSymbol))
        {
            return;
        }

        // Get the syntax references
        var syntaxReferences = namedTypeSymbol.DeclaringSyntaxReferences;
        if (syntaxReferences.Length == 0)
        {
            return;
        }

        var syntaxReference = syntaxReferences[0];
        var syntaxTree = syntaxReference.SyntaxTree;

        // Skip auto-generated files
        if (syntaxTree.IsAutoGeneratedFile())
        {
            return;
        }

        // Get the class declaration
        var classDeclaration = syntaxReference.GetSyntax(context.CancellationToken);
        if (classDeclaration is not ClassDeclarationSyntax classDecl)
        {
            return;
        }

        // Get the expected embedded resource name (fully qualified class name + .kusto)
        var fullyQualifiedName = namedTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));
        var expectedResourceName = $"{fullyQualifiedName}.kusto";

        // Get the file path of the class
        var classFilePath = syntaxTree.FilePath;
        if (string.IsNullOrEmpty(classFilePath))
        {
            return;
        }

        // Calculate the expected .kusto file name (same name as class file but .kusto extension)
        var classFileName = GetFileNameWithoutExtension(classFilePath);
        var expectedKustoFileName = $"{classFileName}.kusto";

        // Check if a .kusto file with the expected name exists in AdditionalFiles
        // .kusto files must be configured as <AdditionalFiles Include="**/*.kusto" /> in .csproj
        var additionalFiles = context.Options.AdditionalFiles;
        var kustoFileExists = additionalFiles
            .Any(file => !string.IsNullOrEmpty(file.Path) &&
                         GetFileName(file.Path).Equals(expectedKustoFileName, StringComparison.OrdinalIgnoreCase));

        if (!kustoFileExists)
        {
            // Report diagnostic on the class identifier
            var diagnostic = Diagnostic.Create(
                Rule,
                classDecl.Identifier.GetLocation(),
                namedTypeSymbol.Name,
                expectedResourceName);

            context.ReportDiagnostic(diagnostic);
        }
    }

    private static string GetFileName(string path)
    {
        var lastSlash = Math.Max(path.LastIndexOf('/'), path.LastIndexOf('\\'));
        return lastSlash >= 0 ? path.Substring(lastSlash + 1) : path;
    }

    private static string GetFileNameWithoutExtension(string path)
    {
        var fileName = GetFileName(path);
        var lastDot = fileName.LastIndexOf('.');
        return lastDot >= 0 ? fileName.Substring(0, lastDot) : fileName;
    }

    private static bool InheritsFromKustoScript(INamedTypeSymbol typeSymbol)
    {
        var baseType = typeSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.Name == Constants.KustoScriptBaseClassName)
            {
                return true;
            }

            baseType = baseType.BaseType;
        }

        return false;
    }
}
