namespace Atc.Kusto.Analyzer.Rules.Usage;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class MissingKustoScriptResourceAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor Rule = new(
        RuleIdentifierConstants.Usage.MissingKustoScriptResource,
        title: "Missing .kusto embedded resource file",
        messageFormat: "Class '{0}' inherits from KustoScript but the corresponding embedded resource '{1}' was not found. Ensure the .kusto file exists and is marked as an embedded resource.",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Classes inheriting from KustoScript must have a corresponding .kusto file as an embedded resource with a name matching the fully qualified class name.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.MissingKustoScriptResource));

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];

    public override void Initialize(AnalysisContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var namedTypeSymbol = (INamedTypeSymbol)context.Symbol;

        if (!ShouldAnalyzeSymbol(namedTypeSymbol))
        {
            return;
        }

        var syntaxReference = GetValidSyntaxReference(namedTypeSymbol);
        if (syntaxReference is null || syntaxReference.SyntaxTree.IsAutoGeneratedFile())
        {
            return;
        }

        var identifier = GetTypeIdentifier(syntaxReference, context.CancellationToken);
        if (identifier is null)
        {
            return;
        }

        var classFilePath = syntaxReference.SyntaxTree.FilePath;
        if (string.IsNullOrEmpty(classFilePath))
        {
            return;
        }

        var fullyQualifiedName = namedTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));
        var expectedResourceName = $"{fullyQualifiedName}.kusto";

        if (!KustoFileExists(context.Options.AdditionalFiles, classFilePath))
        {
            // Report diagnostic on the class/record identifier
            var diagnostic = Diagnostic.Create(
                Rule,
                identifier.Value.GetLocation(),
                namedTypeSymbol.Name,
                expectedResourceName);

            context.ReportDiagnostic(diagnostic);
        }
    }

    private static bool ShouldAnalyzeSymbol(INamedTypeSymbol namedTypeSymbol)
    {
        // Skip if this is an abstract class, interface, or not a class/record
        if (namedTypeSymbol.IsAbstract || (namedTypeSymbol.TypeKind != TypeKind.Class && namedTypeSymbol.TypeKind != TypeKind.Struct))
        {
            return false;
        }

        return InheritsFromKustoScript(namedTypeSymbol);
    }

    private static SyntaxReference? GetValidSyntaxReference(INamedTypeSymbol namedTypeSymbol)
    {
        var syntaxReferences = namedTypeSymbol.DeclaringSyntaxReferences;
        return syntaxReferences.Length > 0 ? syntaxReferences[0] : null;
    }

    private static SyntaxToken? GetTypeIdentifier(SyntaxReference syntaxReference, CancellationToken cancellationToken)
    {
        var declaration = syntaxReference.GetSyntax(cancellationToken);

        return declaration switch
        {
            ClassDeclarationSyntax classDecl => classDecl.Identifier,
            RecordDeclarationSyntax recordDecl => recordDecl.Identifier,
            _ => null,
        };
    }

    private static bool KustoFileExists(ImmutableArray<AdditionalText> additionalFiles, string classFilePath)
    {
        var classFileName = classFilePath.GetFileNameWithoutExtension();
        var classDirectory = classFilePath.GetDirectoryName();
        var expectedKustoFileName = $"{classFileName}.kusto";

        // Check if a .kusto file with the expected name exists in AdditionalFiles
        // .kusto files must be configured as <AdditionalFiles Include="**/*.kusto" /> in .csproj
        // Match by both filename and directory to handle multiple files with the same name
        return additionalFiles.Any(file =>
        {
            if (string.IsNullOrEmpty(file.Path))
            {
                return false;
            }

            var fileName = file.Path.GetFileName();
            if (!fileName.Equals(expectedKustoFileName, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            var fileDirectory = file.Path.GetDirectoryName();
            return fileDirectory.Equals(classDirectory, StringComparison.OrdinalIgnoreCase);
        });
    }

    private static bool InheritsFromKustoScript(INamedTypeSymbol typeSymbol)
    {
        var baseType = typeSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.Name == Constants.KustoScriptBaseClassName)
            {
                return true;
            }

            baseType = baseType.BaseType;
        }

        return false;
    }
}