namespace Atc.Kusto.Analyzer.Rules.Usage;

/// <summary>
/// Analyzer that validates projection fields in .kusto files match the result contract type.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ProjectionMismatchAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor ProjectionFieldNotFoundRule = new(
        RuleIdentifierConstants.Usage.ProjectionFieldNotFound,
        title: "Projection field not found in result type",
        messageFormat: "Projected field '{0}' is not found in result type '{1}'. This will cause a runtime deserialization error.",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "All fields in the Kusto | project statement must exist as properties in the result contract type to ensure successful deserialization.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.ProjectionFieldNotFound));

    private static readonly DiagnosticDescriptor ResultPropertyNotProjectedRule = new(
        RuleIdentifierConstants.Usage.ResultPropertyNotProjected,
        title: "Result type property not projected",
        messageFormat: "Property '{0}' in result type '{1}' is not included in the projection. The property will have its default value at runtime.",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "For clarity and to avoid runtime surprises, consider projecting all properties defined in the result contract type.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.ResultPropertyNotProjected));

    private static readonly DiagnosticDescriptor MissingFinalProjectionRule = new(
        RuleIdentifierConstants.Usage.MissingFinalProjection,
        title: "Missing final project statement",
        messageFormat: "Query for '{0}' does not end with an explicit '| project' statement. Consider adding one to clearly define the result contract.",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Best practice: End queries with an explicit '| project' statement to clearly define which fields map to the result contract.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.MissingFinalProjection));

    private static readonly DiagnosticDescriptor ProjectionFieldNamingMismatchRule = new(
        RuleIdentifierConstants.Usage.ProjectionFieldNamingMismatch,
        title: "Projection field naming mismatch",
        messageFormat: "Projected field '{0}' uses snake_case but result type '{1}' has PascalCase property '{2}'. The deserializer won't match these automatically.",
        RuleCategoryConstants.Usage,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Kusto field names using snake_case (e.g., 'customer_key') won't automatically deserialize to PascalCase properties (e.g., 'CustomerKey'). Use matching names or aliases.",
        helpLinkUri: RuleIdentifierHelper.GetHelpUri(RuleIdentifierConstants.Usage.ProjectionFieldNamingMismatch));

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
        => [ProjectionFieldNotFoundRule, ResultPropertyNotProjectedRule, MissingFinalProjectionRule, ProjectionFieldNamingMismatchRule];

    public override void Initialize(AnalysisContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var namedTypeSymbol = (INamedTypeSymbol)context.Symbol;

        if (!KustoAnalyzerHelper.ShouldAnalyzeSymbol(namedTypeSymbol))
        {
            return;
        }

        // Only analyze types with a result type (KustoQuery<T> or KustoStreamingQuery<T>)
        var resultType = KustoAnalyzerHelper.GetResultType(namedTypeSymbol);
        if (resultType is null)
        {
            return;
        }

        var syntaxReference = KustoAnalyzerHelper.GetSyntaxReference(namedTypeSymbol);
        if (syntaxReference is null || syntaxReference.SyntaxTree.IsAutoGeneratedFile())
        {
            return;
        }

        var classFilePath = syntaxReference.SyntaxTree.FilePath;
        if (string.IsNullOrEmpty(classFilePath))
        {
            return;
        }

        var kustoFile = KustoAnalyzerHelper.FindKustoFile(context.Options.AdditionalFiles, classFilePath);
        if (kustoFile is null)
        {
            // No .kusto file found - ATCK301 will handle this
            return;
        }

        var kustoText = kustoFile.GetText(context.CancellationToken);
        if (kustoText is null)
        {
            return;
        }

        var kustoContent = kustoText.ToString();
        if (string.IsNullOrEmpty(kustoContent))
        {
            // Empty .kusto file - ATCK305 will handle this
            return;
        }

        var location = KustoAnalyzerHelper.GetDiagnosticLocation(syntaxReference, context.CancellationToken);
        if (location is null)
        {
            return;
        }

        // Try to parse final projection
        var projectedFields = Parsing.KustoProjectionParser.ParseFinalProjection(kustoContent);
        if (projectedFields is null)
        {
            // No final project statement - report ATCK308
            ReportMissingFinalProjection(context, location, namedTypeSymbol.Name);
            return;
        }

        // Get result type properties
        var resultProperties = KustoAnalyzerHelper.GetPublicPropertyNames(resultType);

        // Validate projection against contract
        ValidateProjection(context, location, projectedFields, resultProperties, resultType.Name);
    }

    private static void ReportMissingFinalProjection(
        SymbolAnalysisContext context,
        Location location,
        string className)
    {
        var diagnostic = Diagnostic.Create(
            MissingFinalProjectionRule,
            location,
            className);

        context.ReportDiagnostic(diagnostic);
    }

    private static void ValidateProjection(
        SymbolAnalysisContext context,
        Location location,
        IReadOnlyList<string> projectedFields,
        IReadOnlyList<string> resultProperties,
        string resultTypeName)
    {
        // Check for projected fields not in result type (ATCK306 - Error)
        // or naming mismatch (ATCK309 - Warning)
        foreach (var field in projectedFields)
        {
            var matchingProperty = resultProperties.FirstOrDefault(
                p => p.Equals(field, StringComparison.OrdinalIgnoreCase));

            if (matchingProperty is null)
            {
                // Check if this might be a snake_case to PascalCase mismatch
                var potentialMatch = FindPotentialNamingMatch(field, resultProperties);
                if (potentialMatch is not null)
                {
                    // Report ATCK309 - naming mismatch (Warning)
                    var diagnostic = Diagnostic.Create(
                        ProjectionFieldNamingMismatchRule,
                        location,
                        field,
                        resultTypeName,
                        potentialMatch);

                    context.ReportDiagnostic(diagnostic);
                }
                else
                {
                    // Report ATCK306 - field not found (Error)
                    var diagnostic = Diagnostic.Create(
                        ProjectionFieldNotFoundRule,
                        location,
                        field,
                        resultTypeName);

                    context.ReportDiagnostic(diagnostic);
                }
            }
        }

        // Check for result properties not in projection (ATCK307 - Info)
        foreach (var property in resultProperties)
        {
            var matchingField = projectedFields.FirstOrDefault(
                f => f.Equals(property, StringComparison.OrdinalIgnoreCase));

            if (matchingField is null)
            {
                // Also check if there's a snake_case version that was reported as ATCK309
                var snakeCaseMatch = projectedFields.FirstOrDefault(
                    f => ConvertSnakeCaseToPascalCase(f).Equals(property, StringComparison.OrdinalIgnoreCase));

                if (snakeCaseMatch is null)
                {
                    var diagnostic = Diagnostic.Create(
                        ResultPropertyNotProjectedRule,
                        location,
                        property,
                        resultTypeName);

                    context.ReportDiagnostic(diagnostic);
                }
            }
        }
    }

    /// <summary>
    /// Finds a potential property match for a snake_case field name.
    /// </summary>
    private static string? FindPotentialNamingMatch(string field, IReadOnlyList<string> properties)
    {
        // Only check if the field contains underscores (snake_case)
        if (!field.Contains('_'))
        {
            return null;
        }

        var pascalCaseField = ConvertSnakeCaseToPascalCase(field);

        return properties.FirstOrDefault(
            p => p.Equals(pascalCaseField, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Converts a snake_case string to PascalCase.
    /// Example: "customer_key" -> "CustomerKey"
    /// </summary>
    private static string ConvertSnakeCaseToPascalCase(string snakeCase)
    {
        if (string.IsNullOrEmpty(snakeCase))
        {
            return snakeCase;
        }

        var parts = snakeCase.Split('_');
        var result = new System.Text.StringBuilder();

        foreach (var part in parts)
        {
            if (part.Length > 0)
            {
                result.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    result.Append(part.Substring(1).ToLowerInvariant());
                }
            }
        }

        return result.ToString();
    }
}