<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Queries\CustomerSalesQuery.kusto" />
    <None Remove="Queries\CustomersQuery.kusto" />
    <None Remove="Queries\CustomersStreamingQuery.kusto" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Queries\CustomerSalesQuery.kusto" />
    <EmbeddedResource Include="Queries\CustomersQuery.kusto" />
    <EmbeddedResource Include="Queries\NycTaxiTripsStreamingQuery.kusto" />
    <EmbeddedResource Include="Queries\CustomersStreamingQuery.kusto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Atc.Kusto\Atc.Kusto.csproj" />
  </ItemGroup>

</Project>
