name: Build & Publish atc-kusto CLI

on:
  push:
    tags: [ 'atc-kusto@v*.*.*' ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLEASE_PAT }}

      - name: ⚙️ Setup dotnet 9.0.x
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: '9.0.x'

      - name: 🧹 Clean
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      - name: 🔁 Restore packages
        run: dotnet restore src/Atc.Kusto.CLI/Atc.Kusto.CLI.csproj

      - name: 🛠️ Build CLI in release mode
        run: dotnet build src/Atc.Kusto.CLI/Atc.Kusto.CLI.csproj -c Release --no-restore /p:UseSourceLink=true

      - name: 🗳️ Pack CLI for release
        run: dotnet pack src/Atc.Kusto.CLI/Atc.Kusto.CLI.csproj -c Release --no-restore -o ${GITHUB_WORKSPACE}/packages /p:PublicRelease=true

      - name: 📦 Push package to NuGet
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          dotnet nuget push ${GITHUB_WORKSPACE}/packages/atc-kusto*.nupkg -k "$NUGET_KEY" -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
